config/routes.rb
Rails.application.routes.draw do
  get 'site/login'
  get 'site/adm'
  get 'site/index'
  get 'site/menu'
  post 'site/confirm'

  get 'orders/showadmin'
  get 'orders/starters'
  get 'orders/soups'
  get 'orders/courses'
  get 'orders/desserts'
  get 'orders/beverages'

  root 'site#index'
  resources :orders
  resources :orders do
  	resources :order_foods
  end
  resources :admins
  resources :foods
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
	attr_accessor :password
	#EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
	validates :login, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
	# validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
	validates :password, :confirmation => true, :length => { :in => 6..20 } #password_confirmation attr
	validates :name,:surname, :presence => true

	before_save :encrypt_password
	after_save :clear_password


	def encrypt_password
		if password.present?
			require 'digest/sha1'
			self.encrypted_password = Digest::SHA1.hexdigest(password)
		end
	end
	def clear_password
		self.password = nil
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
	validates :name, :price, :presence => true
end

app/models/order.rb
class Order < ApplicationRecord
	validates :name, :surname, :street, :number, :city, :phone, :presence => true
	has_many :order_food
end

app/models/order_food.rb
class OrderFood < ApplicationRecord
  belongs_to :order
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
  before_action :set_admin, only: [:show, :edit, :update, :destroy]

  def index
    @admins = Admin.all
  end

  def show
  end

  def new
    @admin = Admin.new
  end

  def edit
  end

  def create
    @admin = Admin.new(admin_params)
      if @admin.save
        redirect_to @admin, notice: 'Admin was successfully created.' 
      else
         render :new
    end
  end

  def update
      if @admin.update(admin_params)
       redirect_to @admin, notice: 'Admin was successfully updated.' 
      
      else
        render :edit 
      end
  end

  def destroy
    @admin.destroy
    redirect_to admins_url, notice: 'Admin was successfully destroyed.'
  end

  private
    def set_admin
      @admin = Admin.find(params[:id])
    end

    def admin_params
      params.require(:admin).permit(:login, :password, :name, :surname)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_filter :get_user

  def get_user
    @current_user = session[:current_user]
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  before_action :set_food, only: [:show, :edit, :update, :destroy]

  def index
    @foods = Food.all
  end

  def show
  end

  def new
    @food = Food.new
  end

  def edit
  end

  def create
    @food = Food.new(food_params)
      if @food.save
       redirect_to @food, notice: 'Food was successfully created.' 
      else
       render :new 
      end
  end

  def update
    
      if @food.update(food_params)
         redirect_to @food, notice: 'Food was successfully updated.' 
      else
        render :edit 
      end
  end

  def destroy
    @food.destroy
     redirect_to foods_url, notice: 'Food was successfully destroyed.' 
  end

  private
    def set_food
      @food = Food.find(params[:id])
    end

    def food_params
      params.require(:food).permit(:name, :food_type, :price)
    end
end

app/controllers/order_foods_controller.rb
class OrderFoodsController < ApplicationController
	def create
    @order = Order.find(params[:order_id])
    if params[:order_food][:food_name]!='skip'
    	@order_food = @order.order_food.create(order_food_params)
    end
    if params[:order_food][:nextpage]=='show'
    	redirect_to @order
    else
    	redirect_to controller: 'orders', action: params[:order_food][:nextpage], order_id: @order.id, y: params[:order_food][:food_name]
    end
  end
 
  private
    def order_food_params
      params.require(:order_food).permit(:food_name, :amount)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  def index
    @orders = Order.all
  end

  def starters
    @foods = Food.where(food_type: 'Starters')
    @order = Order.find(params[:order_id])
  end

  def soups
    @foods = Food.where(food_type: 'Soups')
    @order = Order.find(params[:order_id])
  end
  def courses
    @foods = Food.where(food_type: 'Main Courses')
    @order = Order.find(params[:order_id])
  end
  def desserts
    @foods = Food.where(food_type: 'Desserts')
    @order = Order.find(params[:order_id])
  end
  def beverages
    @beverages = Food.where(food_type: 'Beverages')
    @beers = Food.where(food_type: 'Beers')
    @order = Order.find(params[:order_id])
  end

  def show
    if params[:order_id]
      @order = Order.find(params[:order_id])
    else
      @order = Order.find(params[:id])
    end
  end
  def showadmin
    
  end

  def new
    @order = Order.new
  end

  def edit
  end

  def create
    @order = Order.new(order_params)

      if @order.save
        redirect_to :action => 'starters', notice: 'Order was successfully created.', order_id: @order.id 
      else
         render :new
      end
  end

  def update
      if @order.update(order_params)
        redirect_to @order, notice: 'Order was successfully updated.' 
      else
        render :edit 
    end
  end

  def destroy
    @order.destroy
     redirect_to orders_url, notice: 'Order was successfully destroyed.' 
  end

  private

    def set_order
      @order = Order.find(params[:id])
    end

    def order_params
      params.require(:order).permit(:name, :surname, :street, :number, :city, :phone)
    end
    def order_food_params
      params.require(:order_food).permit(:food_name, :order)
    end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  def index
  end
  def menu
  	@starters = Food.where(food_type: 'Starters')
  	@courses = Food.where(food_type: 'Main Courses')
  	@soups = Food.where(food_type: 'Soups')
  	@desserts = Food.where(food_type: 'Desserts')
  	@beverages = Food.where(food_type: 'Beverages')
  	@beers = Food.where(food_type: 'Beers')
  end
  def adm
    if !@current_user.present? 
      redirect_to controller: 'site', action: 'login', notice: 'You must by log-in!' 
    end
  end
  def login
  end
  def confirm
    #require 'digest/sha1'
    password = Digest::SHA1.hexdigest(params[:password])
    @admin = Admin.where(login: params[:login]).try(:first)
    if @admin.present? 
      if @admin.encrypted_password == password
        session[:current_user] = @admin
        redirect_to controller: 'site', action: 'adm'
      else
        redirect_to controller: 'site', action: 'login', notice: 'Wrong password or login!' 
      end
    else
      redirect_to controller: 'site', action: 'login', notice: 'Wrong password or login!' 
    end
  end
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/foods_helper.rb
module FoodsHelper
end

app/helpers/order_food_helper.rb
module OrderFoodHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/admins/_form.html.erb
<%= form_for(admin) do |f| %>
  <% if admin.errors.any? %>
<% admin.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>

  <div class="field">
    <%= f.label :login %>
    <%= f.text_field :login %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :surname %>
    <%= f.text_field :surname %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<section id="intro" class="main">
<h1>Editing Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>
</section>

app/views/admins/index.html.erb
<section id="intro" class="main">
<p id="notice"><%= notice %></p>

<h1>Admins</h1>

<table>
  <thead>
    <tr>
      <th>Login</th>
      <th>Name</th>
      <th>Surname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admins.each do |admin| %>
      <tr>
        <td><%= admin.login %></td>
        <td><%= admin.name %></td>
        <td><%= admin.surname %></td>
        <td><%= link_to 'Show', admin %></td>
        <td><%= link_to 'Edit', edit_admin_path(admin) %></td>
        <td><%= link_to 'Destroy', admin, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back', site_adm_path %>
<%= link_to 'New Admin', new_admin_path %>
</section>

app/views/admins/new.html.erb
<section id="intro" class="main">
<h1>New Admin</h1>

<%= render 'form', admin: @admin %>

<%= link_to 'Back', admins_path %>
</section>

app/views/admins/show.html.erb
<section id="intro" class="main">
<p id="notice"><%= notice %></p>

<p>
  <strong>Login:</strong>
  <%= @admin.login %>
</p>

<p>
  <strong>Name:</strong>
  <%= @admin.name %>
</p>

<p>
  <strong>Surname:</strong>
  <%= @admin.surname %>
</p>
<%= @admin.encrypted_password %>
<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>
</section>

app/views/foods/_form.html.erb
<%= form_for(food) do |f| %>
  <% if food.errors.any? %>
  <% food.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :food_type %>
    <%= f.select :food_type, options_for_select([
        ["Starters"],
        ["Main Courses"], 
        ["Soups"],
        ["Desserts"],
        ["Beverages"],
        ["Beers"]
      ], food.food_type) %>
  </div>
  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/foods/edit.html.erb
<section id="intro" class="main">
<h1>Editing Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Show', @food %> |
<%= link_to 'Back', foods_path %>
</section>

app/views/foods/index.html.erb
<section id="intro" class="main">
<p id="notice"><%= notice %></p>

<h1>Foods</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Food type</th>
      <th>Price</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @foods.each do |food| %>
      <tr>
        <td><%= food.name %></td>
        <td><%= food.food_type %></td>
        <td><%= food.price %></td>
        <td><%= link_to 'Show', food %></td>
        <td><%= link_to 'Edit', edit_food_path(food) %></td>
        <td><%= link_to 'Destroy', food, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Back', site_adm_path %>
<%= link_to 'New Food', new_food_path %>
</section>

app/views/foods/new.html.erb
<section id="intro" class="main">
<h1>New Food</h1>

<%= render 'form', food: @food %>

<%= link_to 'Back', foods_path %>
</section>

app/views/foods/show.html.erb
<section id="intro" class="main">
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @food.name %>
</p>

<p>
  <strong>Food type:</strong>
  <%= @food.food_type %>
</p>

<p>
  <strong>Price:</strong>
  <%= @food.price %>
</p>

<%= link_to 'Edit', edit_food_path(@food) %> |
<%= link_to 'Back', foods_path %>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Czech Kitchen</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <header id="header" class="alt">
      <div class="inner">
        <h1>Welcome to Czech Restaurant</h1>
        <p>coś fajnego</p>
      </div>
    </header>
    <div id="wrapper">
      <%= yield %>
    <footer id="footer">
      <span><%= link_to 'Start', root_url %></span>
      <span><%= link_to 'Login', :controller => :site, :action => :login %></span>
      <p class="copyright">&copy; Czech Restaurant. Created by: Baran Wojciech, Ciupiński Dariusz, Paprocka Ida, Maziarz Szymon</p>
    </footer>

    </div>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
   <% order.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :surname %>
    <%= f.text_field :surname %>
  </div>

  <div class="field">
    <%= f.label :street %>
    <%= f.text_field :street %>
  </div>

  <div class="field">
    <%= f.label :number %>
    <%= f.text_field :number %>
  </div>

  <div class="field">
    <%= f.label :city %>
    <%= f.text_field :city %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="actions">
    <%= f.submit 'Next->Starters', class: "button1" %>
  </div>
<% end %>

app/views/orders/beverages.html.erb
<section id="intro" class="main">
<h1>Chosse Beverages and Beers</h1>
<%= form_for([@order, @order.order_food.build]) do |f| %>

<table class="table">
<thead>
	<tr><td>Beverages</td><td>Price</td><td>Amount</td></tr>
</thead>
<tbody>
    <% @beverages.each do |food| %>
    <tr><td><%= food.name %> </td><td><%= food.price %>Kc</td><td><%= f.radio_button :food_name, food.name %></td></tr>
    <% end %>
    <tr><td>Beers</td><td>Price</td><td>Amount</td></tr>
    <% @beers.each do |food| %>
    <tr><td><%= food.name %> </td><td><%= food.price %>Kc</td><td><%= f.radio_button :food_name, food.name %></td></tr>
    <% end %>
    <tr><td COLSPAN=2>Skip</td><td><%= f.radio_button :food_name, 'skip', :checked=>true %></td></tr>
</tbody>
</table>
 <div class="actions">
    <%= f.submit 'Finish' %>
  </div>
  <%= f.hidden_field :nextpage, :value =>'show' %>
<% end %>
</section>

app/views/orders/courses.html.erb
<section id="intro" class="main">
<h1>Chosse Main Courses</h1>
<%= form_for([@order, @order.order_food.build]) do |f| %>

<table class="table">
<thead>
	<tr><td>Name</td><td>Price</td><td>Amount</td></tr>
</thead>
<tbody>
    <% @foods.each do |food| %>
    <tr><td><%= food.name %> </td><td><%= food.price %>Kc</td><td><%= f.radio_button :food_name, food.name %></td></tr>
    <% end %>
    <tr><td COLSPAN=2>Skip</td><td><%= f.radio_button :food_name, 'skip', :checked=>true %></td></tr>
</tbody>
</table>
 <div class="actions">
 <div class="actions">
	 <%= button_tag(type: 'submit', class: "button big") do %>
	 Next <i class="fa fa-arrow-right"></i> Desserts
	<% end %>
    
  </div>
  </div>
  <%= f.hidden_field :nextpage, :value =>'desserts' %>
<% end %>
</section>

app/views/orders/desserts.html.erb
<section id="intro" class="main">
<h1>Chosse Desserts</h1>
<%= form_for([@order, @order.order_food.build]) do |f| %>

<table class="table">
<thead>
	<tr><td>Name</td><td>Price</td><td>Amount</td></tr>
</thead>
<tbody>
    <% @foods.each do |food| %>
    <tr><td><%= food.name %> </td><td><%= food.price %>Kc</td><td><%= f.radio_button :food_name, food.name %></td></tr>
    <% end %>
    <tr><td COLSPAN=2>Skip</td><td><%= f.radio_button :food_name, 'skip', :checked=>true %></td></tr>
</tbody>
</table>
 <div class="actions">
 <div class="actions">
	 <%= button_tag(type: 'submit', class: "button big") do %>
	 Next <i class="fa fa-arrow-right"></i> Beverages
	<% end %>
    
  </div>
  </div>
  <%= f.hidden_field :nextpage, :value =>'beverages' %>
<% end %>
</section>

app/views/orders/edit.html.erb
<section id="intro" class="main">
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>
</section>

app/views/orders/index.html.erb
<section id="intro" class="main">
<p id="notice"><%= notice %></p>

<h1>Orders</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Surname</th>
      <th>Street</th>
      <th>Number</th>
      <th>City</th>
      <th>Phone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.name %></td>
        <td><%= order.surname %></td>
        <td><%= order.street %></td>
        <td><%= order.number %></td>
        <td><%= order.city %></td>
        <td><%= order.phone %></td>
        <td><%= link_to 'Show', order %></td>
        <td><%= link_to 'Edit', edit_order_path(order) %></td>
        <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<%= link_to 'Back', site_adm_path %>
<%= link_to 'New Order', new_order_path %>
</section>

app/views/orders/new.html.erb
<section id="intro" class="main">
<h1>New Order</h1>
<p>Fill form below</p>
<%= render 'form', order: @order %>

</section>

app/views/orders/show.html.erb
<section id="intro" class="main">

<h1>Your order</h1>

<h3>Your data</h3>

<p><%= @order.name %> <%= @order.surname %></p>
<p><%= @order.street %> <%= @order.number %></p>
<p><%= @order.city %></p>
<p>Phone: <%= @order.phone %></p>

<h2>Food list:</h2>
<table>
<% @order.order_food.each do |item| %>
    <tr><td><%= item.food_name %></td></tr>
<% end %>
</table>

<%= link_to 'Back', root_url  , class: "button big" %>
</section>

app/views/orders/showadmin.html.erb
<section id="intro" class="main">
<p id="notice"><%= notice %></p>
<h2>Order address</h2>
<p><%= @order.name %> <%= @order.surname %></p>
<p><%= @order.street %> <%= @order.number %></p>
<p><%= @order.city %></p>
<p>Phone: <%= @order.phone %></p>

<h2>Food list:</h2>
<table>
<% @order.order_food.each do |item| %>
    <tr><td><%= item.food_name %></td></tr>
<% end %>
</table>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>
</section>

app/views/orders/soups.html.erb
<section id="intro" class="main">
<h1>Chosse Soups</h1>
<%= form_for([@order, @order.order_food.build]) do |f| %>
<table class="table">
<thead>
	<tr><td>Name</td><td>Price</td><td>Amount</td></tr>
</thead>
<tbody>
    <% @foods.each do |food| %>
    <tr><td><%= food.name %> </td><td><%= food.price %>Kc</td><td><%= f.radio_button :food_name, food.name %></td></tr>
    <% end %>
    <tr><td COLSPAN=2>Skip</td><td><%= f.radio_button :food_name, 'skip', :checked=>true %></td></tr>
</tbody>
</table>
 <div class="actions">
 <div class="actions">
	 <%= button_tag(type: 'submit', class: "button big") do %>
	 Next <i class="fa fa-arrow-right"></i> Main Courses
	<% end %>
    
  </div>
  </div>
  <%= f.hidden_field :nextpage, :value =>'courses' %>
<% end %>
</section>

app/views/orders/starters.html.erb
<section id="intro" class="main">
<h1>Chosse Starters</h1>
<%= form_for([@order, @order.order_food.build]) do |f| %>

<table class="table">
<thead>
	<tr><td>Name</td><td>Price</td><td>Amount</td></tr>
</thead>
<tbody>
    <% @foods.each do |food| %>
    <tr><td><%= food.name %> </td><td><%= food.price %>Kc</td><td><%= f.radio_button :food_name, food.name %></td></tr>
    <% end %>
    <tr><td COLSPAN=2>Skip</td><td><%= f.radio_button :food_name, 'skip', :checked=>true %></td></tr>
</tbody>
</table>
 <div class="actions">
	 <%= button_tag(type: 'submit', class: "button big") do %>
	 Next <i class="fa fa-arrow-right"></i> Soups
	<% end %>
    
  </div>
  <%= f.hidden_field :nextpage, :value =>'soups' %>
<% end %>
</section>

app/views/site/adm.html.erb
<section id="intro" class="main">
<h1>Control Panel</h1>
<ul class="actions">
      <li><%= link_to 'Orders', {:controller => :orders, :action => :index}, class: "button big" %></li>
      <li><%= link_to 'Food',{ :controller => :foods, :action => :index}, class: "button big" %></li>
      <li><%= link_to 'Admins',{ :controller => :admins, :action => :index}, class: "button big" %></li>
    </ul>
</section>

app/views/site/index.html.erb
<section id="intro" class="main">    
    <ul class="actions">
      <li><%= link_to 'Quick order', {:controller => :orders, :action => :new}, class: "button big" %></li>
      <li><%= link_to 'Menu',{ :controller => :site, :action => :menu}, class: "button big" %></li>
    </ul>    
</section>
  

app/views/site/login.html.erb
<section id="intro" class="main">
<h1>Login</h1>
<p id="error"><%= params[:notice] %></p>
<%= form_tag("/site/confirm", method: "POST") do %>

<div class="field">
    <%= label_tag(:login, "Login") %>
    <%= text_field_tag :login %>
  </div>

  <div class="field">
    <%= label_tag(:login, "Password") %>
    <%= password_field_tag :password %>
  </div>

 <div class="actions">
    <%=  submit_tag("Login") %>
  </div>
<% end %>
</section>

app/views/site/menu.html.erb
<section id="intro" class="main">
<h3>Menu</h3>              
<table>
  <tr>
    <th colspan="2" style= "background-color: #7a6652;color: #fff;">Starters</th>
  </tr>
    <% @starters.each do |food| %>
    <tr>
    <td><%= food.name %></td>
    <td><%= food.price %> Kc</td>
    </tr>
    <% end %>
    <tr>
    <th colspan="2" style= "background-color: #7a6652;color: #fff;">Soups</th>
  </tr>
    <% @soups.each do |food| %>
    <tr>
    <td><%= food.name %></td>
    <td><%= food.price %> Kc</td>
    </tr>
    <% end %>
    <tr>
    <th colspan="2" style= "background-color: #7a6652;color: #fff;">Main Courses</th>
  </tr>
    <% @courses.each do |food| %>
    <tr>
    <td><%= food.name %></td>
    <td><%= food.price %> Kc</td>
    </tr>
    <% end %>
    <tr>
    <th colspan="2" style= "background-color: #7a6652;color: #fff;">Desserts</th>
  </tr>
    <% @desserts.each do |food| %>
    <tr>
    <td><%= food.name %></td>
    <td><%= food.price %> Kc</td>
    </tr>
    <% end %>
    <tr>
    <th colspan="2" style= "background-color: #7a6652;color: #fff;">Beverages</th>
  </tr>
    <% @beverages.each do |food| %>
    <tr>
    <td><%= food.name %></td>
    <td><%= food.price %> Kc</td>
    </tr>
    <% end %>
    <tr>
    <th colspan="2" style= "background-color: #7a6652;color: #fff;">Beers</th>
  </tr>
    <% @beers.each do |food| %>
    <tr>
    <td><%= food.name %></td>
    <td><%= food.price %> Kc</td>
    </tr>
    <% end %> 

  </table>
  <%= link_to 'Back', root_url, class: "button big"%>
</section>